version: "3"

services:
  nexus-product-page:
    image: node:12-alpine
    working_dir: /app
    tty: true
    volumes:
      - .:/app
      - ../paradox/public:/app/public
    entrypoint: npm
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:1234:1234"
    expose:
      - "8000"
      - "1234"
    command: ["run", "build"]
