version: '2'
services:
  kg:
    image: "bluebrain/kg-nexus:latest"
    mem_limit: 512m
    ports:
      - "8080:8080"
    links:
      - cassandra
      - iam
    environment:
      - "CASSANDRA_CONTACT_POINT1=cassandra:9042"
      - "BIND_INTERFACE=0.0.0.0"
      - "PUBLIC_URI=http://localhost:8080"
      - "IAM_BASEURI=http://iam:8080/v0"
      - "SPARQL_BASE_URI=http://blazegraph:9999/bigdata"
      - "SPARQL_ENDPOINT=http://blazegraph:9999/bigdata/sparql"
      - 'JAVA_OPTS=-Xms256m -Xmx256m'
  iam:
    image: "bluebrain/iam-nexus:latest"
    mem_limit: 512m
    entrypoint:
      - /bin/sh
      - -c
      - |
          echo Sleeping for 30 seconds
          sleep 30
          echo Starting IAM
          ./bin/iam-service
    ports:
      - "8081:8080"
    links:
      - cassandra
    environment:
      - "CASSANDRA_CONTACT_POINT1=cassandra:9042"
      - "BIND_INTERFACE=0.0.0.0"
      - "PUBLIC_URI=http://localhost:8081"
      - "IAM_TESTMODE=true"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - 'JAVA_OPTS=-Xms256m -Xmx256m'
  cassandra:
    image: "cassandra:3.11"
    mem_limit: 512m
    environment:
      - "MAX_HEAP_SIZE=256m"
      - "HEAP_NEWSIZE=128m"
  kafka:
    image: "spotify/kafka:latest"
    mem_limit: 256m
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "KAFKA_HEAP_OPTS=-Xmx256m -Xms256m"
  blazegraph:
    image: "bluebrain/blazegraph-nexus:latest"
    mem_limit: 256m
    command: 128m