version: "3.3"
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.0"
    environment:
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      cluster.name: "elasticsearch"
    ports:
      - target: 9200
        published: 9200
        mode: host

  cassandra:
    image: "cassandra:3"
    environment:
      MAX_HEAP_SIZE: "2G"
      HEAP_NEWSIZE: "256m"
      CASSANDRA_BROADCAST_ADDRESS: cassandra
    ports:
      - target: 9042
        published: 9042
        mode: host

  blazegraph:
    image: bluebrain/blazegraph-nexus:2.1.5
    ports:
      - target: 9999
        published: 9999
        mode: host
