version: "3.3"
services:
  kg:
    image: bluebrain/nexus-kg:1.3
    entrypoint: ["wait-for-it.sh", "-s", "-t", "0", "admin:8080", "--", "./bin/kg"]
    environment:
      CASSANDRA_CONTACT_POINT1: "cassandra:9042"
      BIND_INTERFACE: "0.0.0.0"
      PUBLIC_URI: "http://localhost"
      IAM_INTERNAL_IRI: "http://iam:8080"
      IAM_PUBLIC_IRI: "http://localhost"
      ADMIN_INTERNAL_IRI: "http://admin:8080"
      ADMIN_PUBLIC_IRI: "http://localhost"
      SPARQL_BASE_URI: "http://blazegraph:9999/blazegraph"
      ELASTIC_SEARCH_BASE_URI: "http://elasticsearch:9200"
      JAVA_OPTS: "-XX:+UseStringDeduplication -Xms2G -Xmx4G"

  iam:
    image: bluebrain/nexus-iam:1.3
    entrypoint: ["wait-for-it.sh", "-s", "-t", "0", "cassandra:9042", "--", "./bin/iam"]
    environment:
      CASSANDRA_CONTACT_POINT1: "cassandra:9042"
      BIND_INTERFACE: "0.0.0.0"
      PUBLIC_URI: "http://localhost"
      SERVICE_DESCRIPTION_URI: "http://localhost/iam"
      JAVA_OPTS: "-Xms1G -Xmx2G"

  admin:
    image: bluebrain/nexus-admin:1.3
    entrypoint: ["wait-for-it.sh", "-s", "-t", "0", "iam:8080", "--", "./bin/admin"]
    environment:
      CASSANDRA_CONTACT_POINT1: "cassandra:9042"
      BIND_INTERFACE: "0.0.0.0"
      PUBLIC_URI: "http://localhost"
      IAM_INTERNAL_IRI: "http://iam:8080"
      IAM_PUBLIC_IRI: "http://localhost"
      JAVA_OPTS: "-Xms1G -Xmx1G"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.0"
    environment:
      ES_JAVA_OPTS: "-Xms4G -Xmx4G"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"

  cassandra:
    image: "cassandra:3"
    environment:
      MAX_HEAP_SIZE: "4G"
      HEAP_NEWSIZE: "256m"
      CASSANDRA_BROADCAST_ADDRESS: cassandra

  blazegraph:
    image: bluebrain/blazegraph-nexus:2.1.5

  web:
    image: bluebrain/nexus-web:1.3.1
    environment:
      BASE_PATH: "/"
      HOST_NAME: "http://localhost"
      API_ENDPOINT: "http://localhost/v1"

  router:
    image: nginx:stable
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
