version: "3"

services:
  nexus-product-page:
    image: node:14-alpine
    working_dir: /app
    tty: true
    volumes:
      - .:/app
      - ./site:/app/public
    entrypoint: npm
    ports:
      - "8000:8000"
      - "1234:1234"
    expose:
      - "8000"
      - "1234"
    command: ["run", "build"]
