apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: admin
    namespace: nexus
    labels:
      app: admin
      group: service
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: admin
      group: service
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: admin-hd
    namespace: nexus
    labels:
      app: admin
      group: service
  spec:
    ports:
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: prometheus
      port: 9095
      protocol: TCP
      targetPort: 9095
    selector:
      app: admin
      group: service
    clusterIP: None
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: admin
    namespace: nexus
    labels:
      app: admin
      group: service
  spec:
    replicas: 1
    serviceName: admin-hd
    selector:
      matchLabels:
        app: admin
    template:
      metadata:
        namespace: nexus
        labels:
          app: admin
          group: service
      spec:
        containers:
        - name: admin
          image: bluebrain/nexus-admin:latest
          imagePullPolicy: Always
          env:
          - name: PUBLIC_IP
            valueFrom:
              configMapKeyRef:
                name: config
                key: public.ip
          - name: ENVIRONMENT
            value: 'minikube'
          - name: BIND_INTERFACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: REMOTING_INTERFACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PUBLIC_URI
            value: 'http://$(PUBLIC_IP)'
          - name: SERVICE_DESCRIPTION_URI
            value: 'http://$(PUBLIC_IP)/admin'
          - name: PASSIVATION_TIMEOUT
            value: '30 seconds'
          - name: JAVA_OPTS
            value: '-Xms256m -Xmx512m'
          - name: LOG_LEVEL
            value: 'INFO'
          - name: AKKA_LOG_LEVEL
            value: 'INFO'
          - name: CASSANDRA_CONTACT_POINT1
            value: 'cassandra-0.cassandra.nexus.svc.cluster.local'
          - name: CASSANDRA_KEYSPACE
            value: 'admin'
          - name: SEED_NODES
            value: 'admin-0.admin-hd.nexus.svc.cluster.local:2552'
          - name: IAM_BASEURI
            value: 'http://iam.nexus.svc.cluster.local/v1'
          - name: NEXUS_CORE_CONTEXT
            value: 'http://bluebrain.github.io/nexus/contexts/resource.json'
          - name: NEXUS_STD_CONTEXT
            value: 'http://bluebrain.github.io/nexus/contexts/standards.json'
          - name: NEXUS_ERROR_CONTEXT
            value: 'http://bluebrain.github.io/nexus/contexts/error.json'
          - name: SPARQL_BASE_URI
            value: 'http://blazegraph.nexus.svc.cluster.local/blazegraph'
          - name: SPARQL_NAMESPACE
            value: 'admin'
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: 'kafka-0.kafka.nexus.svc.cluster.local:9092'
          command:
          - '/bin/bash'
          - '-c'
          - '/bin/bash /opt/docker/bin/admin-service -Doverride.remoting.interface=$REMOTING_INTERFACE.admin-hd.nexus.svc.cluster.local'
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 2552
            name: remoting
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 5
            successThreshold: 1
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: remoting
            failureThreshold: 5
            successThreshold: 1
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        dnsPolicy: ClusterFirst
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    name: admin
    namespace: nexus
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: admin
            servicePort: 8080
          path: /v1/orgs
        - backend:
            serviceName: admin
            servicePort: 8080
          path: /v1/projects
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    name: admin-direct
    namespace: nexus
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: admin
            servicePort: 8080
          path: /admin
