apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: iam
    namespace: nexus
    labels:
      app: iam
      role: iam
      group: service
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: iam
      role: iam
      group: service
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: iam-hd
    namespace: nexus
    labels:
      app: iam
      role: iam
      group: service
  spec:
    ports:
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    selector:
      app: iam
      role: iam
      group: service
    clusterIP: None
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: iam
    namespace: nexus
    labels:
      app: iam
      role: iam
      group: service
  spec:
    replicas: 1
    serviceName: iam-hd
    selector:
      matchLabels:
        app: iam
    template:
      metadata:
        namespace: nexus
        labels:
          app: iam
          role: iam
          group: service
      spec:
        containers:
        - name: iam
          image: bluebrain/nexus-iam:1.0
          imagePullPolicy: Always
          env:
          - name: PUBLIC_IP
            valueFrom:
              configMapKeyRef:
                name: config
                key: public.ip
          - name: ENVIRONMENT
            value: 'minikube'
          - name: BIND_INTERFACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: REMOTING_INTERFACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PUBLIC_URI
            value: 'http://$(PUBLIC_IP)'
          - name: SERVICE_DESCRIPTION_URI
            value: 'http://$(PUBLIC_IP)/iam'
          - name: HTTP_PREFIX
            value: 'v1'
          - name: PASSIVATION_TIMEOUT
            value: '1 second'
          - name: JAVA_OPTS
            value: '-Xms256m -Xmx512m'
          - name: LOG_LEVEL
            value: 'INFO'
          - name: CASSANDRA_CONTACT_POINT1
            value: 'cassandra-0.cassandra.nexus.svc.cluster.local'
          - name: CASSANDRA_KEYSPACE
            value: 'iam'
          - name: SEED_NODES
            value: 'iam-0.iam-hd.nexus.svc.cluster.local:2552'
          - name: IAM_TESTMODE
            value: 'true'
          command:
          - '/bin/bash'
          - '-c'
          - '/opt/docker/bin/iam -Doverride.remoting.interface=$REMOTING_INTERFACE.iam-hd.nexus.svc.cluster.local'
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 2552
            name: remoting
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 5
            successThreshold: 1
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: remoting
            failureThreshold: 5
            successThreshold: 1
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1Gi
        dnsPolicy: ClusterFirst
        terminationGracePeriodSeconds: 30
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    name: iam
    namespace: nexus
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: iam
            servicePort: 8080
          path: /v1/acls
        - backend:
            serviceName: iam
            servicePort: 8080
          path: /v1/identities
        - backend:
            serviceName: iam
            servicePort: 8080
          path: /v1/realms
        - backend:
            serviceName: iam
            servicePort: 8080
          path: /v1/permissions
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    name: iam-direct
    namespace: nexus
  spec:
    rules:
    - http:
        paths:
        - backend:
            serviceName: iam
            servicePort: 8080
          path: /iam