version: "3.3"
services:
  delta_migration:
    depends_on:
      - cassandra
    image: bluebrain/nexus-delta:latest
    environment:
      KAMON_ENABLED: "false"
      MIGRATE_DATA: "true"
      SCHEMA_VALIDATION_DISABLED: "true"
      DISABLE_INDEXING: "true"
      DELTA_PLUGINS: "/opt/docker/plugins/"
    entrypoint: [ "bin/wait-for-it.sh", "-s", "-t", "0", "cassandra:9042", "--", "./bin/delta-app",
                  "-Xms3G -Xmx3G",
                  "-Dapp.http.interface=0.0.0.0",
                  "-Dapp.http.base-uri=http://delta:8080/v1",
                  "-Dakka.persistence.cassandra.events-by-tag.first-time-bucket=20190204T00:00",
                  "-Dakka.persistence.cassandra.events-by-tag.max-message-batch-size=1000",
                  "-Dakka.persistence.cassandra.events-by-tag.scanning-flush-interval=10s",
                  "-Dapp.database.cassandra.contact-points.1=cassandra:9042" ]
    ports:
      - "8080"

  delta_indexing:
    depends_on:
      - cassandra
    image: bluebrain/nexus-delta:latest
    environment:
      KAMON_ENABLED: "false"
      SCHEMA_VALIDATION_DISABLED: "true"
      DELTA_PLUGINS: "/opt/docker/plugins/"
    entrypoint: ["bin/wait-for-it.sh", "-s", "-t", "0", "cassandra:9042", "--", "./bin/delta-app",
                 "-Xms2G -Xmx2G",
                 "-Dapp.http.interface=0.0.0.0",
                 "-Dapp.http.base-uri=http://delta:8080/v1",
                 "-Dmigration.replay.first-time-bucket=20190204T00:00",
                 "-Dplugins.storage.storages.remote-disk.enabled=true",
                 "-Dplugins.elasticsearch.base=http://elasticsearch:9200",
                 "-Dplugins.blazegraph.base=http://blazegraph:9999/blazegraph",
                 "-Dapp.database.cassandra.contact-points.1=cassandra:9042"]
    ports:
      - "8080"

  blazegraph:
    image: bluebrain/blazegraph-nexus:2.1.5
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -XX:MaxDirectMemorySize=300m -Xms1g -Xmx1g -XX:+UseG1GC"
    ports:
      - "9999"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      ES_JAVA_OPTS: "-Xmx1G"
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9200"

  cassandra:
    image: cassandra:3.11.8
    command: "sh /cassandra-init/init.sh"
    environment:
      JVM_OPTS: "-Xms5g -Xmx5g -Dcassandra.initial_token=0 -Dcassandra.skip_wait_for_gossip_to_settle=0"
      MAX_HEAP_SIZE: "5G"
      HEAP_NEWSIZE: "200m"
      CASSANDRA_BROADCAST_ADDRESS: cassandra
      CASSANDRA_NUM_TOKENS: 1
    healthcheck:
      test: ["CMD", "cqlsh","-e describe keyspaces"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - "./cassandra-init:/cassandra-init"
      - "/Users/dumas/cassandra:/cassandra-backups"