version: "3.3"
services:
  delta:
    depends_on:
      - cassandra
    image: bluebrain/nexus-delta:latest
    environment:
      KAMON_ENABLED: "false"
      MIGRATE_DATA: "true"
      DELTA_PLUGINS: "/opt/docker/plugins/"
    entrypoint: ["bin/wait-for-it.sh", "-s", "-t", "0", "cassandra:9042", "--", "./bin/delta-app",
                 "-Xms5G -Xmx5G",
                 "-Dapp.http.interface=0.0.0.0",
                 "-Dapp.http.base-uri=http://delta:8080/v1",
                 "-Dakka.persistence.cassandra.events-by-tag.first-time-bucket=20190204T00:00",
                 "-Dakka.persistence.cassandra.events-by-tag.max-message-batch-size=1000",
                 "-Dakka.persistence.cassandra.events-by-tag.scanning-flush-interval=10s",
                 "-Dapp.database.cassandra.contact-points.1=cassandra:9042"]
    ports:
      - "8080"

  cassandra:
    image: cassandra:3.11.8
    command: "sh /cassandra-init/init.sh"
    environment:
      JVM_OPTS: "-Xms3g -Xmx3g -Dcassandra.initial_token=0 -Dcassandra.skip_wait_for_gossip_to_settle=0"
      MAX_HEAP_SIZE: "3G"
      HEAP_NEWSIZE: "200m"
      CASSANDRA_BROADCAST_ADDRESS: cassandra
      CASSANDRA_NUM_TOKENS: 1
    healthcheck:
      test: ["CMD", "cqlsh","-e describe keyspaces"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - "./cassandra-init:/cassandra-init"
      - "/Users/dumas/cassandra:/cassandra-backups"