version: "3.3"
services:
  kg:
    image: "bluebrain/kg-nexus:latest"
    environment:
      - "CASSANDRA_CONTACT_POINT1=cassandra:9042"
      - "BIND_INTERFACE=0.0.0.0"
      - "PUBLIC_URI=http://localhost"
      - "IAM_BASEURI=http://iam:8080/v0"
      - "SPARQL_BASE_URI=http://blazegraph:9999/blazegraph"
      - "SPARQL_ENDPOINT=http://blazegraph:9999/blazegraph/sparql"
      - "ELASTIC_BASE_URI=http://elasticsearch:9200"
      - "JAVA_OPTS=-Xms2G -Xmx4G"

  iam:
    image: "bluebrain/iam-nexus:latest"
    entrypoint:
      - /bin/sh
      - -c
      - |
          echo Sleeping for 30 seconds
          sleep 30
          echo Starting IAM
          ./bin/iam-service
    environment:
      - "CASSANDRA_CONTACT_POINT1=cassandra:9042"
      - "BIND_INTERFACE=0.0.0.0"
      - "PUBLIC_URI=http://localhost"
      - "IAM_TESTMODE=true"
      - "ELASTIC_BASE_URI=http://elasticsearch:9200"
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "JAVA_OPTS=-Xms1G -Xmx3G"

  elasticsearch:
    image: "elasticsearch:latest"
    environment:
      - "ES_JAVA_OPTS=-Xms3G -Xmx3G"

  cassandra:
    image: "cassandra:3.11"
    environment:
      - "MAX_HEAP_SIZE=3G"
      - "HEAP_NEWSIZE=300m"

  kafka:
    image: "spotify/kafka:latest"
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "KAFKA_HEAP_OPTS=-Xms1G -Xmx3G"

  blazegraph:
    image: "nawer/blazegraph:2.1.5"
    environment:
      - "JAVA_XMS=1G"
      - "JAVA_XMX=4G"

  landing-page:
    image: bluebrain/nexus-landing-page:latest
    environment:
      - "BASE_PATH="
      - "BASE_URI=http://localhost"

  explorer:
    image: bluebrain/nexus-explorer:latest
    environment:
      - "BASE_PATH=/explorer"
      - "BASE_URI=http://localhost"

  router:
    image: "nginx:stable-alpine"
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
        mode: global
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx:
    file: ./nginx.conf