name: Continuous Integration CLI
on:
  push:
    branches:
      - master
    paths:
      - 'cli/**'
      - 'build.sbt'
      - 'project/**'
  pull_request:
    paths:
      - 'cli/**'
      - 'build.sbt'
      - 'project/**'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Cache Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-coursier-scala-
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: StaticAnalysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project cli" clean scalafmtCheck test:scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project cli" clean coverage test coverageReport coverageAggregate
  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CI: true
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Cache Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-coursier-scala-
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: Publish
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project cli" releaseEarly
      - name: PublishToDockerHub
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false docker:publishLocal
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push bluebrain/nexus-cli:latest
      - name: RecordCoverage
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project cli" clean coverage test coverageReport coverageAggregate
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}