name: Delta Plugins unit tests
on:
  pull_request:
    paths:
      - 'delta/kernel/**'
      - 'delta/plugins/**'
      - 'delta/rdf/**'
      - 'delta/sdk/**'
      - 'delta/sourcing-psql/**'
      - 'delta/testkit/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta-plugins.yml'
jobs:
  run:
    if: github.event_name == 'pull_request'
    runs-on: it
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Unit tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            plugins-unit-tests-with-coverage
