name: Delta Ship unit tests
on:
  pull_request:
    paths:
      - 'ship/**'
      - 'delta/kernel/**'
      - 'delta/rdf/**'
      - 'delta/sdk/**'
      - 'delta/sourcing-psql/**'
      - 'delta/testkit/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta-ship.yml'
jobs:
  run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create /tmp/ship folder
        run: mkdir -p /tmp/ship
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
          check-latest: true
      - name: Clean, build Delta & Storage images
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            app/Docker/publishLocal
      - name: Start services
        run: docker-compose -f tests/docker/docker-compose.yml up -d
      - name: Waiting for Delta to start
        run: |
          URL="http://localhost:8080/v1/version"
          curl --connect-timeout 3 --max-time 5 --retry 30 --retry-all-errors --retry-delay 3 --retry-max-time 90 $URL
      - name: Unit tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            ship/testOnly *Suite
      - name: Integration tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            ship/it:testOnly *Spec
