name: Delta Plugins
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta-plugins.yml'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: it
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            coverage \
            plugins/test \
            plugins/coverageReport
