name: Delta Ship unit tests
on:
  pull_request:
    paths:
      - 'ship/**'
      - 'delta/kernel/**'
      - 'delta/rdf/**'
      - 'delta/sdk/**'
      - 'delta/sourcing-psql/**'
      - 'delta/testkit/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta-ship.yml'
jobs:
  run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
          check-latest: true
      - name: Unit tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            ship-unit-tests-with-coverage
