name: Continuous Integration Delta
on:
  push:
    branches:
      - master
    paths:
      - 'sourcing/**'
      - 'rdf/**'
      - 'delta/**'
      - 'build.sbt'
      - 'project/**'
  pull_request:
    paths:
      - 'sourcing/**'
      - 'rdf/**'
      - 'delta/**'
      - 'build.sbt'
      - 'project/**'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Cache Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-coursier-scala-
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - name: StaticAnalysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" clean scalafmtCheck test:scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: |
          grep -qF 'bucket.my-domain.com' /etc/hosts || echo "127.0.0.1 bucket.my-domain.com" | sudo tee -a /etc/hosts
          grep -qF 'bucket2.my-domain.com' /etc/hosts || echo "127.0.0.1 bucket2.my-domain.com" | sudo tee -a /etc/hosts
          sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" clean coverage test coverageReport coverageAggregate
  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CI: true
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Cache Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-coursier-scala-
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - name: PublishToBintray
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" releaseEarly
      - name: PublishToDockerHub
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" docker:publishLocal
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push bluebrain/nexus-delta:latest
      - name: RecordCoverage
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" clean coverage test coverageReport coverageAggregate
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}