name: Delta Plugins
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta-plugins.yml'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - name: Tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            coverage \
            plugins/test \
            plugins/coverageReport
