name: Delta Plugins unit tests
on:
  pull_request:
    paths:
      - 'akka/**'
      - 'delta/kernel/**'
      - 'delta/plugins/**'
      - 'delta/rdf/**'
      - 'delta/sdk/**'
      - 'delta/sourcing-psql/**'
      - 'delta/testkit/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta-plugins.yml'
jobs:
  run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04-arm
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
          check-latest: true
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Pull docker images
        run: |
          docker compose \
            -f tests/docker/blazegraph.yml \
            -f tests/docker/elasticsearch.yml \
            -f tests/docker/localstack.yml \
            -f tests/docker/rdf4j.yml \
            -f tests/docker/postgres.yml pull
      - name: Unit tests
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            plugins-unit-tests-with-coverage
