name: Delta
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-delta.yml'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: it
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Static Analysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" clean scalafmtCheck Test/scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project delta" clean coverage test coverageReport coverageAggregate
