name: Delta ElasticSearch Plugin
on:
  pull_request:
    paths:
      - 'delta/kernel/**'
      - 'delta/rdf/**'
      - 'delta/sdk/**'
      - 'delta/sdk-views/**'
      - 'delta/sdk-testkit/**'
      - 'delta/sourcing/**'
      - 'delta/testkit/**'
      - 'delta/plugins/elasticsearch/**'
      - 'build.sbt'
      - 'project/**'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Coursier Cache
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Static Analysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project elasticsearchPlugin" clean scalafmtCheck test:scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project elasticsearchPlugin" clean coverage test coverageReport coverageAggregate
