name: Delta Execute Integration Tests
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'storage/**'
      - 'tests/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-execute-integration-tests.yml'
jobs:
  tests:
    runs-on: it
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean Build
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean
      - name: Build Delta Image
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project app" Docker/publishLocal
      - name: Build Storage Image
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project storage" Docker/publishLocal
      - name: Start services
        run: docker-compose -f tests/docker/docker-compose-ci.yml up -d && sleep 120
      - name: Test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" test
      - name: Stop Docker
        if: ${{ always() }}
        run: docker-compose -f tests/docker/docker-compose-ci.yml down
      - name: Cleanup Docker Containers
        if: ${{ always() }}
        run: |
          for container in `docker images | grep none | awk '{print $3}'`; do
            echo "Deleting container: $container";
            docker rmi $container;
          done
