name: Delta Integration Tests
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'storage/**'
      - 'tests/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-integration-tests.yml'
jobs:
  review:
    runs-on: it
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clean, build Delta & Storage images
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            app/Docker/publishLocal \
            storage/Docker/publishLocal
      - name: Start services
        run: docker compose -f tests/docker/docker-compose-ci.yml up -d && sleep 60
      - name: Test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" test
      - name: Stop & clean Docker
        if: ${{ always() }}
        run: docker compose -f tests/docker/docker-compose-ci.yml down -rmi "local" --volumes