name: Delta Integration Tests
on:
  push:
    branches:
      - master
    paths:
      - 'delta/**'
      - 'storage/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-integration-tests.yml'
jobs:
  tests:
    runs-on: nise-cg029
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean Build
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean
      - name: Build Delta Image
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project app" Docker/publishLocal
      - name: Build Storage Image
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project storage" Docker/publishLocal
      - name: Test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" 'set composeFile := "tests/docker/docker-compose-ci.yml"' dockerComposeTest
      - name: Stop Docker
        if: ${{ always() }}
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" "dockerComposeStop"
