name: Delta Integration Tests
on:
  pull_request:
    paths:
      - 'delta/**'
      - 'storage/**'
      - 'tests/**'
      - 'build.sbt'
      - 'project/**'
      - '.github/workflows/ci-integration-tests.yml'
jobs:
  run:
    runs-on: it
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Clean, build Delta & Storage images
        run: |
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            clean \
            app/Docker/publishLocal \
            storage/Docker/publishLocal
      - name: Start services
        run: docker-compose -f tests/docker/docker-compose.yml up -d && sleep 70
      - name: Waiting for Delta to start
        run: |
          URL="http://localhost:8080/v1/version"
          curl --connect-timeout 3 --max-time 5 --retry 20 --retry-all-errors --retry-delay 3 --retry-max-time 60 $URL
      - name: Test
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" test
      - name: Stop & clean Docker
        if: ${{ always() }}
        run: docker-compose -f tests/docker/docker-compose.yml down --rmi "local" --volumes