name: Release
on:
  release:
    types: [published]
jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI_RELEASE: publishSigned
      RELEASE_TO_SONATYPE: true
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PGP_SECRET: ${{ secrets.PGP_SECRET }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Publish To Sonatype
        run: sbt -Dsbt.color=always -Dsbt.supershell=false ci-release
      - name: Publish To Dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            app/Docker/publish \
            storage/Docker/publish