name: Continuous Integration RDF
on:
  push:
    branches:
      - master
    paths:
      - 'rdf/**'
      - 'build.sbt'
      - 'project/**'
  pull_request:
    paths:
      - 'rdf/**'
      - 'build.sbt'
      - 'project/**'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier
        uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: StaticAnalysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project rdf" clean scalafmtCheck test:scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project rdf" clean coverage test coverageReport coverageAggregate
  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CI: true
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Coursier
        uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12
        with:
          java-version: adopt@1.11
      - name: Publish
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project rdf" releaseEarly
      - name: RecordCoverage
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project rdf" clean coverage test coverageReport coverageAggregate
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
