name: Continuous Integration Release
on:
  release:
    types: [published]
jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CI: true
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Cache Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-scala-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-coursier-scala-
      - name: Setup Scala
        uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11
      - name: SetVersion
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:11})
      - name: Publish
        run: sbt -Dsbt.color=always -Dsbt.supershell=false ";set Docker/version := \"${{ env.VERSION }}\"; releaseEarly; docker:publishLocal"
      - name: PublishToDockerHub
        run: |
        echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker push bluebrain/nexus-cli:${{ env.VERSION }}
      - name: RecordCoverage
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean coverage test coverageReport coverageAggregate
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}


