name: Release Docker
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  release:
    if: false  # Disabling the release workflow for now
    #if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
          check-latest: true
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Set up proxy for docker buildx
        run: |
          echo http_proxy=${http_proxy} >> $GITHUB_ENV
          echo https_proxy=${https_proxy} >> $GITHUB_ENV
          echo no_proxy=${no_proxy} >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            env.http_proxy=${{ env.http_proxy }}
            env.https_proxy=${{ env.https_proxy }}
            "env.no_proxy='${{ env.no_proxy}}'"
      - name: Publish To Dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          sbt -Dsbt.color=always -Dsbt.supershell=false \
            app/Docker/publish