name: Continuous Integration Release
on:
  release:
    types: [published]
jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      CI: true
      BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Coursier Cache
        uses: coursier/cache-action@v5
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Set Version
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:11})
      - name: Publish
        run: sbt -Dsbt.color=always -Dsbt.supershell=false ";set Docker/version := \"${{ env.VERSION }}\"; releaseEarly; docker:publishLocal"
      - name: Publish To DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push bluebrain/nexus-cli:${{ env.VERSION }}
          docker push bluebrain/nexus-delta:${{ env.VERSION }}
          docker push bluebrain/nexus-storage:${{ env.VERSION }}
      - name: Record Coverage
        run: sbt -Dsbt.color=always -Dsbt.supershell=false clean coverage test coverageReport coverageAggregate
      - name: Report Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
