name: Publish Sonatype test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/ci-snapshot-test.yml'
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      RELEASE_TO_SONATYPE: true
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      PGP_SECRET: ${{ secrets.PGP_SECRET }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - name: Publish Storage Service to Sonatype
        run: sbt -Dsbt.color=always -Dsbt.supershell=false ci-release