name: Delta Storage Plugin
on:
  pull_request:
    paths:
      - 'delta/kernel/**'
      - 'delta/rdf/**'
      - 'delta/sdk/**'
      - 'delta/sourcing/**'
      - 'delta/sdk-testkit/**'
      - 'delta/testkit/**'
      - 'delta/plugins/storage/**'
      - 'build.sbt'
      - 'project/**'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Coursier Cache
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Static Analysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project storagePlugin" clean scalafmtCheck test:scalafmtCheck scalafmtSbtCheck scapegoat
      - name: Tests
        run: |
          grep -qF 'bucket.my-domain.com' /etc/hosts || echo "127.0.0.1 bucket.my-domain.com" | sudo tee -a /etc/hosts
          grep -qF 'bucket2.my-domain.com' /etc/hosts || echo "127.0.0.1 bucket2.my-domain.com" | sudo tee -a /etc/hosts
          grep -qF 'bucket3.my-domain.com' /etc/hosts || echo "127.0.0.1 bucket3.my-domain.com" | sudo tee -a /etc/hosts
          sbt -Dsbt.color=always -Dsbt.supershell=false "project storagePlugin" clean coverage test coverageReport coverageAggregate
