name: Continuous Integration Tests
on:
  pull_request:
    paths:
      - 'delta/kernel/**'
      - 'delta/sdk-testkit/**'
      - 'tests/**'
      - 'build.sbt'
      - 'project/**'
jobs:
  review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Coursier Cache
        uses: coursier/cache-action@v5
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Static Analysis
        run: sbt -Dsbt.color=always -Dsbt.supershell=false "project tests" clean scalafmtCheck test:scalafmtCheck test:compile scapegoat
